# Run the full test suite (in `tests/`) on every push of Python code 
# to GitHub, on a range of Python versions and OS'es.

name: CI

# Avoid markdown edits triggering the testing machine.
on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            python-version: 3.9
            # NumPy's `__init__` errors with Py 3.9 on MacOS.
            # Ignore this combo for our tests until 'they' fix that.

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download repo at latest commit
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update package installer
        run: python -m pip install --upgrade pip

      - name: Install our package
        run: pip install .

      - name: Install testing requirements
        run: pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest
